<?php

// =====================================================================

// !!  路由文件由 owl-admin 自动生成，请不要手动修改。

// !!  Route file auto generated by owl-admin, don't modify it manually.

// =====================================================================

use Slowlyo\OwlAdmin\Admin;
use Illuminate\Routing\Router;
use Illuminate\Support\Facades\Route;

Route::group([
    'domain'     => Admin::config('admin.route.domain'),
    'prefix'     => Admin::config('admin.route.prefix'),
    'middleware' => Admin::config('admin.route.middleware'),
], function (Router $router) {
    // 客户表
    $router->resource('customers', \App\Admin\Controllers\CustomerController::class);
    // 放款表
    $router->resource('loans', \App\Admin\Controllers\LoanController::class);
    // 抵押物
    $router->resource('collaterals', \App\Admin\Controllers\CollateralController::class);

});